CREATE DATABASE IF NOT EXISTS EQUIPE_PROGRAMACAO;
USE EQUIPE_PROGRAMACAO;

CREATE TABLE LINGUAGEM(
    ID_LINGUAGEM INT PRIMARY KEY,
    NOME_DA_LINGUAGEM VARCHAR (50),
    EMPRESA VARCHAR (100),
    CRIADOR VARCHAR (100),
    DATA_DE_CRIACAO DATE
);
CREATE TABLE PROGRAMADORES(
    ID_PROGRAMADOR INT PRIMARY KEY AUTO_INCREMENT,
    NOME_DO_PROGRAMADOR VARCHAR (100)
);

CREATE TABLE PROJETO(
    ID_PROJETO INT PRIMARY KEY,
    NOME_DO_PROJETO VARCHAR (100)
);
CREATE TABLE PROGAMADOR_PROJETO (
    ID_PROJETO INT,
    ID_PROGRAMADOR INT,
    FOREIGN KEY (ID_PROJETO) REFERENCES PROJETO (ID_PROJETO),
    FOREIGN KEY (ID_PROGRAMADOR) REFERENCES PROGRAMADORES (ID_PROGRAMADOR)
);

CREATE TABLE LINGUAGEM_PROJETO (
    ID_LINGUAGEM INT,
    ID_PROJETO INT
);
CREATE TABLE LINGUAGENS_DO_PROGRAMADOR (
    ID_PROGRAMADOR INT,
    ID_LINGUAGEM INT
);

ALTER TABLE LINGUAGEM_PROJETO
ADD CONSTRAINT  FK_LINGUAGEM_PROJETO
FOREIGN KEY (ID_LINGUAGEM) REFERENCES LINGUAGEM (ID_LINGUAGEM);

ALTER TABLE LINGUAGEM_PROJETO
ADD CONSTRAINT  FK_LINGUAGEM_PROJETO
FOREIGN KEY (ID_PROJETO) REFERENCES PROJETO (ID_PROJETO);

ALTER TABLE LINGUAGENS_DO_PROGRAMADOR
ADD CONSTRAINT  FK_LINGUAGENS_DO_PROGRAMADOR
FOREIGN KEY (ID_PROGRAMADOR) REFERENCES PROGRAMADORES (ID_PROGRAMADOR);

ALTER TABLE LINGUAGENS_DO_PROGRAMADOR
ADD CONSTRAINT  FK_LINGUAGENS_DO_PROGRAMADOR
FOREIGN KEY (ID_LINGUAGEM) REFERENCES LINGUAGENS (ID_LINGUAGEM);

