CREATE DATABASE EQUIPE_PROGRAMACAO;

CREATE TABLE LINGUAGEM(
    ID_LINGUAGEM PRIMARY KEY INT,
    NOME_DA_LINGUAGEM VARCHAR (50),
    EMPRESA VARCHAR (100),
    CRIADOR VARCHAR (100),
    DATA_DE_CRIACAO DATE
);
CREATE TABLE PROGRAMADORES(
    ID_PROGRAMADOR PRIMARY KEY INT
    NOME_DO_PROGRAMADOR VARCHAR (100)
    );

CREATE TABLE PROJETO(
    ID_PROJETO PRIMARY KEY INT,
    NOME_DO_PROJETO VARCHAR (100),
);
CREATE TABLE PRORMADOR_PROJETO (
    ID_PROJETO INT,
    ID_PROGRAMADOR INT,
);

CREATE TABLE LINGUAGE_PROJETO (
    ID_LINGUAGEM INT,
    ID_PROJETO INT,
);
CREATE TABLE LINGUAGENS_DO_PROGRAMADOR (
    ID_PROGRAMADOR INT,
    ID_LINGUAGEM INT,
);

